version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: mock_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Gitian620@
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile  # Use the combined Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=Gitian620@
      - HT_MODE=RECORD
      - JAVA_OPTS=-javaagent:/opt/agent/mocking-library-agent.jar

volumes:
  agent-volume: